### PR TITLE
docs: add missing comma

### PR DESCRIPTION
**Pull request by schmelto**
docs/Architectural_Overview_c93afb5.md

### CODE REVIEW

**Comment by Paolaufer** [comment]
Hi,
Can you tell me where you found a missing comma?

**Comment by schmelto** [comment]
> Hi,
> Can you tell me where you found a missing comma?

```
SAP Business Application Studio is part of SAP BTP and the SAP Multi-cloud offering \(AWS, Azure, Alibaba, …\).
```

See the changes also directly in the git diff

**Comment by Paolaufer** [comment]
Updated the doc.
You will see it fixed with the next release.
Thanks for the heads up.

**Comment by schmelto** [comment]
https://github.com/SAP-samples/devtoberfest-2021/issues/13#issuecomment-932304978
SAP Community ID: `schmelto`

**Pull request closed without merging**
