### PR TITLE
Added link to the restriction of trial accounts

### PR DESCRIPTION
**Pull request by ceedee666**
As the 2gb size limit is mentioned here I added a link to the list of all restrictions applying to trial accounts.

### CODE REVIEW

**Comment by Paolaufer** [comment]
Hi @ceedee666,
Thank you for your input.
The topic is specifically for learning about the Dev Space Manager.
We prefer to have the information for working in a Trial account under the respective chapter. 
We will not change this for the moment but will be happy to reassess in the future.

**Comment by ceedee666** [comment]
Hi @Paolaufer, 
but I didn't duplicate the information. Instead I added a link to the section describing the trail accounts limitations. IMHO it would be good to link to this documentation as some of these limitations influence the way the dev space manager works. for example, in the trial account I can only create 2 spaces and I can only start one.

Having the link here would allow people reading the documentation to easily find out about the limitations. Currently, one would need to dig through the navigation tree to find the right document. 

Maybe it would be even better to remove the specific mentioning of the 2gb limitations of the trail account and simply mention that different limitations apply to trial accounts and provide the link. 
Christian

**Comment by Paolaufer** [comment]
OK, point well made :)
I'll merge your changes and you will be able to see the link on our next docu release.

**Review by Paolaufer — APPROVED** [review]

**Review by qmacro — APPROVED** [review]
LGTM!

**Pull request merged**
