### PR TITLE
docs: add links to java and node.js

### PR DESCRIPTION
**Pull request by schmelto**
SAP Community ID: `schmelto`

### CODE REVIEW

**Comment by schmelto** [comment]
https://people.sap.com/schmelto

**Comment by schmelto** [comment]
@ShiraManas when I will see the badge in my sap community profile?

**Comment by ShiraManas** [comment]
Hi! I will look into this and make sure you receive your badge as soon as possible.

**Comment by schmelto** [comment]
> Hi! I will look into this and make sure you receive your badge as soon as possible.

Thanks :)

**Comment by qmacro** [comment]
Hi @schmelto the badges are usually assigned in batch on a weekly basis. So yours is on its way :-) Thanks for your contribution!

**Comment by qmacro** [comment]
Hi @schmelto   - badge assignment is now on its way, my apologies - it's my fault the system is a little slow.

**Pull request merged**
