### PR TITLE
Update Welcome_Page_28f418e.md

### PR DESCRIPTION
**Pull request by greg2git**
From the welcome page, it's not clear if a developer is a paid license or in open source license environment.

### CODE REVIEW

**Comment by Paolaufer** [comment]
Hi @greg2git,
Thank you. Currently you can see if you are in a trial account from the URL or from the note in the Dev Space Manager.
Trial note.
We will look into your suggestion.

I invite you to share feature requests through the SAP Community: https://answers.sap.com/questions/ask.html?primaryTagId=67837800100800007077

**Comment by qmacro** [comment]
Hi @greg2git and thanks for your PR! I've been discussing this with @Paolaufer and I'm not sure of the intent of the PR, so wanted to ask some questions to clarify, so we can work out what (if any) changes might be made to improve things.

You point out that the productive/trial context is not clear from the welcome page itself. This is true. But the change you are suggesting to the Welcome Page content (_"Note: Please ensure that you are in your production and not in the trial account environment"_) doesn't entirely reflect that point; the welcome page is the welcome page and you don't need specifically to be using it productively (as opposed to in trial) at this point in the flow. 

Did you mean that the welcome page *should* show you whether you're working in trial or productively? (If so, I would humbly suggest that this might be more of a feature request, but also point out that you can tell indirectly by looking at the URL - there will be the word "trial" as part of the fully qualified domain name). I might have misunderstood your intentions, though. Can you please clarify?

**Comment by greg2git** [comment]
> Hi @greg2git and thanks for your PR! I've been discussing this with @Paolaufer and I'm not sure of the intent of the PR, so wanted to ask some questions to clarify, so we can work out what (if any) changes might be made to improve things.
> 
> You point out that the productive/trial context is not clear from the welcome page itself. This is true. But the change you are suggesting to the Welcome Page content (_"Note: Please ensure that you are in your production and not in the trial account environment"_) doesn't entirely reflect that point; the welcome page is the welcome page and you don't need specifically to be using it productively (as opposed to in trial) at this point in the flow.
> 
> Did you mean that the welcome page _should_ show you whether you're working in trial or productively? (If so, I would humbly suggest that this might be more of a feature request, but also point out that you can tell indirectly by looking at the URL - there will be the word "trial" as part of the fully qualified domain name). I might have misunderstood your intentions, though. Can you please clarify?

Hi @qmacro 

i think this could be a suggestion or more of a disclaimer. new users, and hence natural help page readers, may not be all that familiar with the distinction of trial vs production and not appreciate the difference in their URL. i'm also concerned that they may only find out later that trial services have limitations like insufficient space and application up times and it's only fair to warn them about it. this will save some frustrations down the road when their development work needs to be moved or they would need to upgrade to get their application up and running. at least, this is the impression i got when using the prior free service on Neo like WebIDE or some tutorials that warn users up front that whatever work they would try would not be applicable in the free trial tier.

does this make sense? 
ty, gm

**Comment by qmacro** [comment]
Hi @greg2git thanks for the reply. To be honest, I'm still not convinced that this information belongs in this generic guide to the Business Application Studio, at least not in this Welcome Page section. Just to make sure we're not misunderstanding, would you like to revise your contribution content so @Paolaufer and I can take another look? Thanks.

**Comment by greg2git** [comment]
Hi @qmacro and @Paolaufer 
i think i'm done making my case and my apologies for being too confusing. 
feel free to reject it as you see fit.
Thank you for your consideration and best regards,
gm

**Comment by Paolaufer** [comment]
Hi @greg2git,
You make perfect sense :)
I presented your thoughts to PM and they are considering it.
I will close the issue since it has now moved to the PM arena. I will be happy to let you know if this is implemented.
Thank you for your contribution!

**Pull request closed without merging**
