### PR TITLE
Update Connecting_to_a_Corporate_Git_Repository_d54ddfc.md

### PR DESCRIPTION
**Pull request by AmauryVanEspen**
Enhance accessibility of picture

### CODE REVIEW

**Comment by Paolaufer** [comment]
Thank you!!!

**Comment by Paolaufer** [comment]
Updated. THanks.

**Comment by AmauryVanEspen** [comment]
Hello @Paolaufer 
I'm looking for Mission badge on my sap profile for feedback and contribution. I believe it does not appear

Could you provide a feedback about it ? Thank you

regards
Amaury

**Comment by Paolaufer** [comment]
Hi Amaury,
Badges are updated manually periodically.
If you have not had your badge assigned next week please let me know.
Regards,
Pao

**Pull request merged**
