### PR TITLE
Extra documentation on git merge in BAS

### PR DESCRIPTION
**Pull request by enric11**
Hi team,

I think it would be interesting to add this documentation to clarify the use of GIT tools on Business Application Studio when performing a merge.

The change I propose is to add a subsection with examples of how the conflicting files look like and the different alternatives that BAS allows to solve it.

I hope that this information could be useful for the users

Thanks in advance
Enric

### CODE REVIEW

**Comment by ShiraManas** [comment]
Thanks for your feedback! I am checking this over with the developers.

**Review by ShiraManas — CHANGES_REQUESTED** [review]
This is amazing feedback and very useful information. I will add this to the documentation.
I've made some small updates to what you wrote. Thanks.

**Comment by ShiraManas** [comment]
> Hi,
> 
> I don't know if I have a problem with this pull request.
> 
> I see this error in the JOB: image
> 
> Is any action necessary on my part?
> 
> Thanks in advance Regards Enric

I believe that we can't merge images in the PR, only text. Is that correct. @je-hal? If so, I can add these images to our documentation and it will be reflected in the GitHub documentation with our next release.

**Comment by enric11** [comment]
https://people.sap.com/enric101

**Comment by enric11** [comment]
I haven't received the badged yet, could it be a communication error?

Thank you very much

**Comment by ShiraManas** [comment]
Hi. The badge is assigned manually. I will check up on this and make sure you get the badge as soon as possible.

**Pull request merged**
